### ISSUE TITLE
Make balsa tkinter threadsafe

### ISSUE THREAD

**Issue by mrice88** [jamesabel/balsa#1]
In python 3 the tkinter module is technically threadsafe, but there are caveats. 

So it is worthwhile to make Balsa account for this, by using the mttkinter library, which replaces tkinter in memory and modifies the Tk class to uses a `Queue.Queue` object for events.  

From the [mttkinter library issues page](https://github.com/RedFantom/mtTkinter/issues/5)...
>Tk is not thread-safe, unless it is built with the thread-safe flag. However, the Tcl-interpreter must also be built with the thread-safe flag to ensure thread-safety for Tkinter.

**Comment by jamesabel** [comment]
Also, add the dialog box handler after the file logger and sentry, just to be safer.

**Comment by jamesabel** [comment]
Fixed in 0a69d2b76a76f1bd279be6f28ee5258da1b03ce0 and cf764f76dbbb5a721f237e90e2bec1b784e90179
